apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beep-rtc.fullname" . }}
  labels:
    {{- include "beep-rtc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "beep-rtc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "beep-rtc.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          env:
            - name: IP_ENDPOINT
              value: "{{ .Values.image.ipEndpoint }}"
            - name: VALUE_PORT_MIN
              value: "{{ .Values.udp.port }}"
            - name: VALUE_PORT_MAX
              value: "{{ .Values.udp.port }}"
            - name: SIGNAL_PORT
              value: "{{ .Values.image.portHTTP }}"
          envFrom:
            - secretRef:
                name: {{ .Values.appSecretName }}            
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.portHTTP }}
              protocol: TCP
            {{- range .Values.ports }}
            - name: "port-{{ . }}"
              containerPort: {{ . }}
              protocol: UDP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
