apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ printf "%s-ingress-udp" (include "beep-rtc.fullname" .) }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - "{{ .Values.udp.entrypointName }}"
  routes:
    - services:
      - name: {{ printf "%s-service" (include "beep-rtc.fullname" $) }}
        port: {{ $.Values.udp.port }}
