replicaCount: 1
image:
  pullPolicy: Always
  portHTTP: 8080
  repository: hugo08/beep-rtc-staging

  ipEndpoint: 162.38.112.211

service:
  type: ClusterIP
  port: 80

resources: {}

ingress:
  enabled: true
  annotations: { traefik.ingress.kubernetes.io/router.entrypoints: web}
  hosts:
    - host: voice-staging.beep.ovh
      paths: ['/']

udp:
  entrypointName: stream1
  port: 33434

ports:
  - 33434


appSecretName: app-secret